<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="WNB.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">
    <p>
    <strong>Why We Need Blood?</strong></p>
<p>
&nbsp;Blood is often called the “lifeline” of the human body because it performs vital functions such as carrying oxygen and nutrients to tissues, regulating body temperature, fighting infections, and removing waste materials. Without blood, the human body cannot survive even for a few minutes. In daily life, most people have enough blood to stay healthy, but during medical emergencies and health conditions, patients may lose a significant amount of blood or require blood components that their bodies cannot produce quickly. In such times, donated blood becomes a lifesaving necessity. There are countless situations where blood is urgently needed. Accident victims, burn patients, and women facing complications during childbirth often require immediate blood transfusions. People undergoing major surgeries or organ transplants need blood to survive through the procedure. Patients with chronic illnesses such as cancer, thalassemia, hemophilia, and severe anemia depend on regular blood 
    transfusions for their treatment. Similarly, those undergoing chemotherapy often lose healthy blood cells and require donated blood to recover. In all these cases, timely availability of blood can make the difference between life and death. An important fact to remember is that blood cannot be manufactured in laboratories or factories; it can only come from generous donors. A single unit of donated blood can be separated into red blood cells, plasma, and platelets, which can help multiple patients at the same time. This makes every donation incredibly valuable. However, the demand for blood is constant and ever-increasing due to the growing number of accidents, medical advancements, and rising health conditions in society. Having an adequate supply of blood in hospitals and blood banks is crucial for saving lives during emergencies, natural disasters, and even pandemics. Without it, many people would be left helpless, and countless lives would be lost. Therefore, voluntary blood 
    donation plays a vital role in ensuring that no patient dies due to lack of blood. In conclusion, we need blood not only for emergencies but also for routine treatments and surgeries. Donated blood is the bridge between life and death for millions of people every year. It is the responsibility of all healthy individuals to contribute to this noble cause so that our communities remain safe and prepared for any medical situation. Truly, donating blood ensures that whenever someone is in need, hope is never out of reach.</p>
</asp:Content>

